PATH="/home/ebigram/perl5/bin:/home/ebigram/.sdkman/candidates/grails/current/bin:/home/ebigram/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Python37/Scripts/:/mnt/c/Program Files/Python37/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Java/jdk1.8.0_211/bin:/mnt/c/Program Files (x86)/vim/vim80:/mnt/c/Users/maibea.SM/scoop/apps/spark/current/bin:/mnt/c/Users/maibea.SM/scoop/apps/zeppelin/current/bin:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files (x86)/IncrediBuild:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Java/jdk1.8.0_211/bin:/mnt/c/Program Files/PowerShell/7-preview/preview:/mnt/c/Program Files/PowerShell/6/:/mnt/c/tools/groovy-2.5.7/bin:/mnt/c/Users/maibea.SM/scoop/apps/oraclejdk/current/bin:/mnt/c/Users/maibea.SM/scoop/apps/nodejs/current/bin:/mnt/c/Users/maibea.SM/scoop/apps/nodejs/current:/mnt/c/Users/maibea.SM/scoop/apps/bloop/current/$dir:/mnt/c/Users/maibea.SM/scoop/apps/python/current/Scripts:/%SPARK_HOME/bin:/mnt/c/Users/maibea.SM/scoop/apps/hadoop-winutils/current/bin:/%ZEPPELIN_HOME/bin:/mnt/c/Users/maibea.SM/scoop/shims:/mnt/c/Users/maibea.SM/AppData/Local/Microsoft/WindowsApps:/mnt/c/tools/Cmder:/mnt/c/tools/neovim/Neovim/bin:/mnt/c/Program Files/Java/jdk1.8.0_201/bin:/mnt/c/Users/maibea.SM/.dotnet/tools:/mnt/c/Program Files (x86)/LinqPad5:/mnt/c/tools/mysql/current/bin:/mnt/c/Users/maibea.SM/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/maibea.SM/AppData/Local/hyper/app-3.0.2/resources/bin:/usr/lib/jvm/java-12-oracle/bin:/usr/lib/jvm/java-12-oracle/db/bin:/home/linuxbrew/.linuxbrew/bin:anaconda3/bin:/usr/lib/jvm/java-12-oracle/bin:/usr/lib/jvm/java-12-oracle/db/bin:/home/linuxbrew/.linuxbrew/bin:anaconda3/bin"
export WINHOME=/mnt/c/Users/maibea.SM/
source ~/.promptline.sh
source ~/.bash_alias

#echo 'netsh winsock reset&&netsh int ip reset all&&netsh winhttp reset proxy &&ipconfig /flushdns' | cmd.exe
#export gateway=$(echo '(Get-NetIPAddress -InterfaceAlias "VEthernet (WSL)" | select -last 1).IPAddress' |powershell.exe -NoProfile -NoLogo | grep 172 | tr -d '\r')
#echo vitovski | sudo -S ip route delete default
#echo vitovski | sudo -S ifconfig eth0 netmask 255.255.240.0; echo vitovski | sudo -S ip route add default via $gateway
